# Generated by Django 2.1.4 on 2018-12-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, db_column='user_name', max_length=10, null=True)),
                ('project_name', models.CharField(blank=True, db_column='project_name', max_length=10, null=True)),
                ('file_title', models.CharField(db_column='file_title', default='', max_length=100)),
                ('file_id', models.CharField(blank=True, db_column='file_id', max_length=20, null=True)),
                ('parent_file_id', models.CharField(blank=True, db_column='parent_file_id', max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='project/%Y/%m/%d/file')),
                ('content', models.TextField(null=True)),
                ('origin_date', models.DateTimeField(blank=True, db_column='Origin_date', null=True)),
                ('final_date', models.DateTimeField(blank=True, db_column='Final_date', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, db_column='project_name', max_length=10, null=True)),
                ('project_password', models.CharField(blank=True, db_column='project_password', max_length=30, null=True)),
                ('admin_password', models.CharField(blank=True, db_column='admin_password', max_length=30, null=True)),
                ('project_root', models.CharField(blank=True, db_column='project_root', max_length=20, null=True)),
                ('schedule', models.TextField(null=True)),
                ('memo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, db_column='project_name', max_length=10, null=True)),
                ('project_password', models.CharField(blank=True, db_column='project_password', max_length=30, null=True)),
                ('user_name', models.CharField(blank=True, db_column='user_name', max_length=10, null=True)),
            ],
        ),
    ]
